name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{github.sha}}"
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from testing"
      
    - name: Execute few commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{env.APPLICATION_NAME}}"
    
    - name: List current folder
      run: ls -la
      
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
    - name: Print Hello Message
      run: echo "Hello World from deploy"
      
    - name: Print Deployment package
      run: echo "Deploy package name:${{env.DEPLOY_PACKAGE_NAME}}"
  
